name: Run on pull req

on:
  pull_request:
    branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 
              uses: actions/checkout@v2
            - name: Install Go Dependencies
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.1'
            - name: Build the project
              run: go build -v
            - name: Run tests
              run: go test -v
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout 
              uses: actions/checkout@v2
            - name: Tag image
              id: tags
              run: echo "::set-output name=sha_version::${{ github.sha }}"  
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/sampleapp:${{ steps.tags.outputs.sha_version }}
    notify:
        runs-on: ubuntu-latest
        needs: [build, deploy]
        steps:
            - name: Notify People
              uses: cl8dep/action-discord@v0
              with:
                webhook: ${{ secrets.DISCORD_NOTIFY }}
                message: 'Build and Deployed Successfully'
            
            
